// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABy6ow7XNj_Wh7ehpaUyjiao5mRx1d4c8',
    appId: '1:916629239711:web:6951c0c58259d2e5c9efaa',
    messagingSenderId: '916629239711',
    projectId: 'practice-todo-example',
    authDomain: 'practice-todo-example.firebaseapp.com',
    storageBucket: 'practice-todo-example.appspot.com',
    measurementId: 'G-V0RTPNT8Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT-pYXFX-kuPjS9tEZdlPggWtjPVtWehQ',
    appId: '1:916629239711:android:2582854b5e9a7029c9efaa',
    messagingSenderId: '916629239711',
    projectId: 'practice-todo-example',
    storageBucket: 'practice-todo-example.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABy6ow7XNj_Wh7ehpaUyjiao5mRx1d4c8',
    appId: '1:916629239711:web:e3e056de12292824c9efaa',
    messagingSenderId: '916629239711',
    projectId: 'practice-todo-example',
    authDomain: 'practice-todo-example.firebaseapp.com',
    storageBucket: 'practice-todo-example.appspot.com',
    measurementId: 'G-77JR1ZP428',
  );

}