// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWnZmiYxJxNLMkClmxf2nuceddNNHH0Do',
    appId: '1:170673707522:web:f1a0ea72c35fe06c5b651b',
    messagingSenderId: '170673707522',
    projectId: 'furever-home-882fd',
    authDomain: 'furever-home-882fd.firebaseapp.com',
    storageBucket: 'furever-home-882fd.firebasestorage.app',
    measurementId: 'G-WMD4KYLV4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQIusxWrWeV4qzkzO7jaCAHI2xLp9oTxk',
    appId: '1:170673707522:android:f4f45aa9fb6ab3675b651b',
    messagingSenderId: '170673707522',
    projectId: 'furever-home-882fd',
    storageBucket: 'furever-home-882fd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWnZmiYxJxNLMkClmxf2nuceddNNHH0Do',
    appId: '1:170673707522:web:5ca1f3aa83f0850f5b651b',
    messagingSenderId: '170673707522',
    projectId: 'furever-home-882fd',
    authDomain: 'furever-home-882fd.firebaseapp.com',
    storageBucket: 'furever-home-882fd.firebasestorage.app',
    measurementId: 'G-ZJECNXHD2B',
  );
}
