name: furever_home_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_cache_manager: ^3.4.1
  http: ^1.3.0
  image_picker: ^1.1.2
  image_picker_web: ^4.0.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
